version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: ./server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PHONE: ${ADMIN_PHONE}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5000:5000"
    command: sh -c "sleep 10 && npx knex migrate:latest && npm start"

  frontend:
    build: ./client
    depends_on:
      - server
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production

  nginx-proxy:
    image: nginx:1.25-alpine
    depends_on:
      - frontend
      - server
    ports:
      - "80:80"
    volumes:
      - /etc/ssl/lv-trans-app.ru:/etc/ssl/lv-trans-app.ru:ro

volumes:
  db_data: